name: tokei_app
description: "Tokei app"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: ^3.6.0
  flutter: ^3.6.0 # Flutter version should be here, separate from dependencies.

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.2.0
  cupertino_icons: ^1.0.8
  universal_io: ^2.0.4
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Italic.ttf
          style: italic
        - asset: assets/fonts/SF-Pro-Text-BoldItalic.otf
          weight: 700
          style: italic
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_28pt-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter_18pt-BoldItalic.ttf
          weight: 700
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff" # Background color of the splash screen (optional, white by default)
  image: "assets/images/logo.png" # Path to your splash screen image
  android: true # Enable splash for Android
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
  ios: true # Enable splash for iOS

